name: ACApp
description: ACAPP

version: 2.9.0+63

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  dio: ^3.0.9
  flutter_web_browser: ^0.11.0
  launch_review: ^2.0.0
  http: ^0.12.0+4
  url_launcher: ^5.4.5

  ## Widgets
  add_2_calendar: ^1.4.0
  big_tip: ^1.1.0
  expand_widget: ^0.2.0+2
  flutter_local_notifications: ^1.4.0
  flutter_map: ^0.8.2
  flutter_markdown: ^0.3.4
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.17.3+1
  row_collection: ^0.2.4
  search_page: ^1.2.0
  sliver_fab: ^1.0.0

  ## Tools
  flutter_i18n: ^0.13.0
  package_info: ^0.4.0+16
  provider: ^4.1.0-dev
  quick_actions: ^0.4.0+2
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  system_setting: ^0.1.3
  getflutter: ^1.0.4

  ## Linter
  lint: ^1.1.1

dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_vector_icons: ^0.2.1
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.2


flutter:
  
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
  assets:
    - assets/flutter_i18n/
    - assets/flowers/

  uses-material-design: true
